language: r
warnings_are_errors: false

before_install:
  - sudo apt-get update
  - printf "\n" | pecl install imagick
  - export LD_FLAGS=-L$HOME/opt/lib
  - export LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib:$HOME/opt/lib
  - export CPATH=$CPATH:$HOME/opt/include

branches:
  only:
    - master
  except:

# Code coverage
r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov(token = "0fe8593a-c2ae-465a-a9f9-c8ac244116e3")'
