language: r
warnings_are_errors: false

branches:
  only:
    - master
  except:

# Code coverage
r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov(token = "5f041826-63f1-47fa-b4a8-9a32633f47fa")'
