language: r
cache: packages
sudo: required
warnings_are_errors: false

r:
  - oldrel
  - release
  - devel

# blacklist
# branches:
#   except:
#     - master

# whitelist
branches:
  only:
    - master
    - release

r_binary_packages:
  - ade4
  - dispRity
  - geometry
  - rgl
  - zoo
  - covr

# addons:
#   apt:
#     packages:
#       - libxml2-dev
      
branches:
  only:
    - master

after_success:
  - Rscript -e 'library(covr); codecov(token = "0fe8593a-c2ae-465a-a9f9-c8ac244116e3")'
