language: r
warnings_are_errors: false

before_install:
  - sudo apt-get update
  - printf "\n" | pecl install imagick
  - pecl install libgit2

branches:
  only:
    - master
  except:

# Code coverage
r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov(token = "0fe8593a-c2ae-465a-a9f9-c8ac244116e3")'
