language: r

cache: packages
warnings_are_errors: false

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
      - sourceline: 'ppa:ubuntugis/ppa'
      - sourceline: 'ppa:xorg-edgers'
    packages:
      - libmagick++-dev
      - libglu1-mesa-dev
      - freeglut3-dev
      - mesa-common-dev

branches:
  only:
    - master

# Code coverage
r_packages:
  - covr
after_success:
  - Rscript -e 'library(covr); codecov(token = "0fe8593a-c2ae-465a-a9f9-c8ac244116e3")'
